### ISSUE TITLE
Make warning about missing flows more persistent

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#10]
Source of the request: https://community.homey.app/t/app-pro-piggy-bank/66677/155?u=frodeheg

**Comment by ugumba** [comment]
Any news on this? I still see the warning about missing price flow.
I've been supplying price points from a flow for months now🙂.

The new "prices" plots also appear completely empty - maybe this is related?
(The maxUse and usage plots appear fine.)

**Comment by frodeheg** [comment]
Stil not implemented.
The prices plots does not appear because prices are not fetched when using flows for price points. Do you think I should separate out the price fetching so it can be used with the flows, or do you prefer just having the price points showing without prices? Or maybe you want to supply your own prices to show there?

**Comment by ugumba** [comment]
Hmm. I've been confusing price value and "price point". I'm supplying the latter, not the former, so the warning is ok, i guess.

**Comment by frodeheg** [comment]
Lol, this is ridiculous.
I already did what I thought I had to do for this ticket on September 11th 2022.
Unfortunately at that time I did it wrong and forgot about the partial implementation.
So, it was actually implemented, I just had to fix it...
