### ISSUE TITLE
Wrong legend in consumption chart

### ISSUE THREAD

**Issue by slasktrat** [frodeheg/no.sparegris#123]
I hovedfanen "Hjem" og underfane "Forbruk" så er søylene lablet korrekt med "Forbruk" i dagsvisning, men i månedsvisning og årsvisning er de lablet "Høyeste timeforbruk"

**Comment by slasktrat** [comment]
Sorry, antar dette er duplikat av #119

**Comment by frodeheg** [comment]
Yes, it will be published soon, thanks for reporting though :-)
