### ISSUE TITLE
Fixed energy prices does not "fetch" more future prices than until midnight

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#21]
Unlike spot prices which are fetched at 13:00-14:00 for the next day, the fixed prices doesn't update before after midnight.
This is a bug

**Comment by frodeheg** [comment]
![image](https://user-images.githubusercontent.com/99914572/196076388-b9c26476-848e-46c3-93b5-8f900736b0a7.png)

**Comment by frodeheg** [comment]
I cannot reproduce this so I wonder if it got fixed by one of the earlier fixes @dooniem, can you confirm? Are the fixed prices cut off at midnight or midnight the next day?

**Comment by dooniem** [comment]
Yes, seems good
![93685AAF-72EC-4F7C-8A5E-F8D19ECA0DC7](https://user-images.githubusercontent.com/9369839/197373232-e2b4bf35-7332-452b-a08a-80c5851708f9.png)

**Comment by frodeheg** [comment]
Ok, I'll close this then. If ever observed again please let me know.
