### ISSUE TITLE
Tibber pulse does not report power / energy in order

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#218]
The code already handle reordered time but the accuracy for the result is reduced. Attempt to improve the accuracy for this case as it obviously happen more often than expected.

**Comment by Norxcode** [comment]
A log dump here for example on frequency... 

+9:36:27.204: The reported power time was from the past. This should only happen when the clock is adjusted.
+9:45:48.676: The reported power time was from the past. This should only happen when the clock is adjusted.
+9:46:18.177: The reported power time was from the past. This should only happen when the clock is adjusted.
+9:46:47.696: The reported power time was from the past. This should only happen when the clock is adjusted.
+9:48:16.316: The reported power time was from the past. This should only happen when the clock is adjusted.
+9:58:19.953: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:0:48.387: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:10:43.338: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:10:53.170: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:12:11.880: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:29:47.675: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:43:5.695: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:43:55.309: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:50:50.450: The reported power time was from the past. This should only happen when the clock is adjusted.
+10:51:0.305: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:11:42.723: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:15:1.278: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:17:28.951: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:18:38.196: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:21:55.362: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:29:39.348: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:29:49.198: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:36:23.298: The reported power time was from the past. This should only happen when the clock is adjusted.
+11:44:37.096: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:12:16.094: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:12:35.790: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:12:45.660: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:25:34.996: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:25:55.076: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:26:4.971: The reported power time was from the past. This should only happen when the clock is adjusted.
+12:49:6.752: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:1:47.330: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:4:54.742: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:15:56.123: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:17:24.679: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:20:12.239: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:22:30.172: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:27:55.471: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:32:11.694: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:33:40.280: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:37:18.955: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:38:58.931: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:40:38.259: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:41:57.051: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:45:13.991: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:46:3.313: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:49:20.686: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:50:9.922: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:52:37.878: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:57:4.137: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:59:12.239: The reported power time was from the past. This should only happen when the clock is adjusted.
+13:59:41.766: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:1:10.592: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:1:49.944: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:2:39.180: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:6:55.535: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:7:25.063: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:8:54.218: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:12:21.922: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:13:1.328: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:17:37.247: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:25:59.641: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:32:5.437: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:40:48.783: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:41:38.045: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:42:7.988: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:42:57.202: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:43:4.506: Failed to reduce power usage by 1000W (number of forced on devices: 3)
+14:44:6.249: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:44:55.880: Failed to reduce power usage by 1000W (number of forced on devices: 3)
+14:45:6.968: Failed to reduce power usage by 1000W (number of forced on devices: 3)
+14:45:18.299: Failed to reduce power usage by 1000W (number of forced on devices: 3)
+14:45:45.120: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:50:51.455: The reported power time was from the past. This should only happen when the clock is adjusted.
+14:56:37.256: The reported power time was from the past. This should only happen when the clock is adjusted.
+15:6:18.288: The reported power time was from the past. This should only happen when the clock is adjusted.
+15:50:53.953: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:3:23.142: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:4:51.696: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:11:6.311: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:11:26.419: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:20:0.209: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:25:36.048: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:26:25.382: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:29:42.617: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:31:21.317: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:32:40.274: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:35:8.019: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:38:25.166: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:38:44.835: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:39:24.192: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:43:41.209: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:45:50.451: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:46:10.108: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:47:9.134: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:48:57.626: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:50:36.120: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:56:32.537: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:58:31.747: The reported power time was from the past. This should only happen when the clock is adjusted.
+16:58:51.694: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:3:47.639: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:5:6.701: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:17:56.030: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:19:24.550: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:28:17.023: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:31:34.735: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:44:36.857: The reported power time was from the past. This should only happen when the clock is adjusted.
+17:48:3.887: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:2:1.818: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:7:47.417: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:9:25.998: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:14:32.475: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:15:31.931: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:20:8.003: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:25:13.432: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:27:12.570: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:39:33.054: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:41:32.049: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:52:3.275: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:52:22.992: The reported power time was from the past. This should only happen when the clock is adjusted.
+18:59:17.929: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:10:10.227: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:11:58.537: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:23:0.330: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:24:19.494: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:29:15.258: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:31:3.750: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:33:2.397: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:35:30.431: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:45:43.371: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:46:52.747: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:52:47.560: The reported power time was from the past. This should only happen when the clock is adjusted.
+19:55:5.451: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:1:40.312: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:13:43.251: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:27:46.090: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:29:54.529: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:30:24.210: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:32:51.844: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:34:40.583: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:35:29.784: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:37:47.798: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:38:56.646: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:42:53.360: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:51:45.975: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:55:12.938: The reported power time was from the past. This should only happen when the clock is adjusted.
+20:56:31.891: The reported power time was from the past. This should only happen when the clock is adjusted.

**Comment by frodeheg** [comment]
Trying to assess the importancy of this fix, @Norxcode :
1) If you look at the estimated energy usage per hour by Piggy in the app settings, how well does it fit with what is reported at elhub.no?
2) Since this causes the app to think that there are time without power. What is the average time reported without power over the day?
3) Is this problem giving huge problems with applications turning itself off, even with 10s intervals for power checking?

A workaround would possibly be:
* Change the meter reader to "from flows"
* Then input the current power whenever it changes to the app 
OR
* Input the current meter value whenever it changes to the app
not both....
The problem arises when both are used

**Comment by frodeheg** [comment]
The above may fix the problem for you, but it may also not fix the problem. The only thing I did was to prevent flow-cards to be able to post power and meter reader updates when you have manually selected a meter reader. So.. in case you had old flows running, then the warnings should now disappear. If not it should still be there...

The change is out for testing at https://homey.app/a/no.sparegris/test in case you want to try.

**Comment by Norxcode** [comment]
> If you look at the estimated energy usage per hour by Piggy in the app settings, how well does it fit with what is reported at elhub.no?

Used Norwegian, so just changed my Homey to English to be able to follow you. - If you meen the graph, "Usage" ? for hourly their are close to same. Looks like the differese is just roundups..  Meaning for 30 march, elhub:  51.706 kWh , PB: 51.526 ---- Looking at hourly like 21:00 - elhub reports: 1.442, PB: 1.443

>Since this causes the app to think that there is time without power. What is the average time reported without power over the day? 

Using same day as the log above was from, 30 March - Time without power 0% , and hourly, 16:00 was 2% without power. - If I am correct, that log above is with utc, and you can actualy see there it happens, +14:46  
This is with the 10s on Tibber polling interval. - I was not seeing it Live on Tibbers own app, however it looks like a "pause" in their graph aswell - So I belive this few minuts actually had issues on their side.
At the same time in the log entries on AC, Turned On: 16:45:17 by sparegris, Turned off: 16:45:18 and back on 16:47:48 by sparegris.

>Is this problem giving huge problems with applications turning themselves off, even with 10s intervals for power checking?

For me personaly it is not a huge problem.  AC is set to PowerON (still the poweroff log entries mentioned above), and only floor heating is the one PB can adjust freely, but they stay on without using energy most of the time as heating from AC is enough. - My Limit is set to 10KWH (winter, and need the charging speed this month). - and Usage is around 1kWh during daytime.  

Rember that it started with a message that Tibber Pulse default value is 30s, and i saw alot of the alarms with Limiting....
After adjusting to 10s, they occours but not the same amount. (not logged, but by obersvations)

>A workaround would possibly be: Change the meter reader to "from flows"
Then input the current power whenever it changes to the app

Just enabled it now to use Power, and changed PB to use Flow. Doing one change at a time.

**Comment by Norxcode** [comment]
>>A workaround would possibly be: Change the meter reader to "from flows"
Then input the current power whenever it changes to the app

>Just enabled it now to use Power, and changed PB to use Flow. Doing one change at a time.

Small update, - Using only Power, and flow as input. No entries in the Diagnostic Logs for last 3 hours. 
Pulse is still set to 10s intervall.. PB is at 47.7 MB now, but that is 3 hour since restart. so will check it later aswell..
version is v0.20.12

Will leave it on like this for some more hours to see if we also get the limit alert,, has been none for the same periode aswell. Do you think this is related issue or continue in this thread with that?

**Comment by Norxcode** [comment]
>From Forum  - Now, I do not have any input from anyone if this was because they was supplying power values to the app with flow cards in addition to the direct power readings (user error) or if it is the Tibber Pulse itself that report power readings out of order / not in synch with the meter reader.

for my setup.  -With the log entries. No flow cards was sending data to PB.  Only using Pulse under Meter Data.

**Comment by frodeheg** [comment]
Thank you. The new version I mentioned in the forum will be pushed out as soon as Athom approves it. It will reset the state to the old behavior (triggered by the 3-star review I just got). I am going on a 1-week Easter holiday tomorrow so I have no time to spare to fix whatever is wrong, thus I pull the emergency brake instead.

**Comment by frodeheg** [comment]
Closing this ticket as the above changes should be sufficient to fix this.
