### ISSUE TITLE
Fix remaining missing translations

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#220]
Apparently there was some missing translations
the drivers/ directory is not translated at all
And Piggy Bank was still the same name in nl and fr

**Comment by frodeheg** [comment]
Still missing drivers/ before we can close this.

**Comment by PeterKawa** [comment]
Done. https://github.com/frodeheg/no.sparegris/pull/224/commits/0130812b75859decf2e2fd9df2f8b1ff8354cf0f
