### ISSUE TITLE
Bug: Car charging not raising power

### ISSUE THREAD

**Issue by dooniem** [frodeheg/no.sparegris#23]
I set it to charge 3kW on 1 hour. When charging started it never raised the circuit current. It was stuck on 7A. So I triggered a flow that raised it to 20A when approx 5min remained of the hour. After the hour changed, it didn’t stop the charging nor lower the circuit current. But maybe the last part happened because I sent trigger to the Easee charger directly and thereby disabled PB?
Could another reason for not raising the power be that 3kW was delivered, or should that not matter?

**Comment by frodeheg** [comment]
Has Piggy ever changed the circuit current for Easee? Even initial circuit current? Or was it only able to change the onoff capability?

How much throttle time did you set?

Does the Easee app have a log where you can see what happens? (not the timeline) I was wondering maybe I am sending invalid current values?

You have marked Easee as a controllable device, didn't you?

I can make a button in the log section for testing where you can see if the Easee charger does change at all and how long the response time is. Should I do this next?

20A is less than 5000W so I suppose that may pass well into the next hour. The app doesn't turn off or turn down current if it's within the limit. It also depends on the priority you put on the charger, something else might have been turned off before it?

**Comment by dooniem** [comment]
> Has Piggy ever changed the circuit current for Easee? 
Yes, but in a previous version when you didn't have the trigger you currently have.
But it wasn't good at changing, it was troublesome. It change to 14A and kept it there, even breaking the tariff.
There might be a bug with the call you make, yes.

> How much throttle time did you set?
Default. 30sec

> You have marked Easee as a controllable device, didn't you?
Yes

> It also depends on the priority you put on the charger, something else might have been turned off before it?
I only have the charger as a controllable device

> Does the Easee app have a log where you can see what happens? 
The Easee integration have 2 types of log.

- Log - Seems to only show successful calls
- Last API error - No history, so I captured some screenshots to hopefully get you oriented

Here's the log for when a new charge session starts. All good it seems.
![image](https://user-images.githubusercontent.com/9369839/196275331-8a012108-8c0a-47b3-a314-9f5389eff0e3.png)

But I do get a lot of errors. Hard to know if I'm able to capture them all since it only shows the last one after I refresh.
Here's one right after a new charge has started:
![image](https://user-images.githubusercontent.com/9369839/196274933-3f550414-f9d8-4820-8fb2-bca02c156810.png)

I've captured some others as well. One mentions dynamic circuit current...
![image](https://user-images.githubusercontent.com/9369839/196275784-65be989f-22b0-4390-ab9a-47e61ac0a38b.png)

and this one:
![image](https://user-images.githubusercontent.com/9369839/196275876-93b695e0-4bc5-49d5-8ee3-644340362cbc.png)

> I can make a button
I'll gladly help, just tell me what to do with the button :D

I could remember wrong, but I think you handle all chargers as they were 3 phased? Could it be a good test to handle it 2 phased?

**Comment by dooniem** [comment]
According to themselves, their servers are operational:
[https://status.easee.com/](url)

**Comment by frodeheg** [comment]
Hmm.... maybe you should share the API call errors with Robert_B in the other chat, seems like the problem is on that side?

**Comment by dooniem** [comment]
My current findings and understanding after my own experiments tonight and Richards input is the following:

Sending onoff is not necessary at all.
Toggle state will work as the on and the off.
Only send toggle at the beginning and at end of planned charging time (or kWh).
Setting the dynamic circuit current to 0 will pause the charge. Or more specific, the charger will report “waiting for smart charge”, just setting a new dynamic circuit current will resume the charging, no extra commands needed. And do course regulating up and down needs no more commands than the dynamic circuit number. 

When starting the charging session, set dynamic circuit to minimum (7A), wait 1 sec, then send toggle. I will try throttle time on 120 sec. And if all this makes it work, experiment on setting it lower.

Could we test this approach?

**Comment by dooniem** [comment]
The one thing I can test tomorrow is how the charger reacts when toggling when the cable is unplugged. If you run my tight proposal and plug in the car after toggle is sent, you will never start charging. Unless you have a flow that only starts PB charging when plugged in. Some users will make flows without that check

**Comment by frodeheg** [comment]
The current code send the onoff=true in the beginning to turn on and whenever un-pausing
Onoff=false is sent whenever pausing and when finished.
The dynamic current is sent immediately after an onoff = true signal and whenever going up and down in current, it never goes below 7 or above 40.

Sounds like you're suggesting that I use onoff=true when starting the charging cycle, onoff=false when stopping the charging cycle and dynamic_current = 0A whenever pausing. If so we need Richard to undo this: https://community.homey.app/t/app-pro-easee-charger/31647/143?u=frodeheg

**Comment by dooniem** [comment]
I did some more testing. I have assumed you specifically sent a toggle call to the API. I'm only now realizing that you only send "onoff=true" and that in turn sends 2 commands to the easee charger:
"Set onoff to true" AND "Toggling charge".
Which is in line with Richards statement:
![image](https://user-images.githubusercontent.com/9369839/196373558-fa219902-4b69-4be8-95af-d52f2b033f5f.png)
 
I see you commented on the thread with Richard to undo the not allowing 0A. My suggestion is to return everything below 6A as 0A, then we're still in line with Easee and we can pause more easily. I thought of that just now, didn't include that in my comment to Richard.

**Comment by dooniem** [comment]
In case you check comments on GitHub before Homey Community. I granted you access to my Easee charger, check the DM for details.

**Comment by frodeheg** [comment]
Thanks, the above fix should fix it... although it seems like your charger is charging with 3.5 kW regardless of what the offered current is set to?
