### ISSUE TITLE
Virtual switches can behave as both thermostat devices and onoff devices, need to distinguish the two...

### ISSUE THREAD

**Issue by PeterKawa** [frodeheg/no.sparegris#230]
Ah, well, I found the file using grep ;-) But I don't see translations in that file, so if you can give me a hint?
![Screenshot from 2023-04-02 18-14-59](https://user-images.githubusercontent.com/74005072/229365304-6c09cae9-053c-4634-a38d-9a2d9a1032fb.png)

Hi Frode,

On the 'controllable devices' tab, the tooltip stays in English. I couldn't find in which file this translation should reside.
Can you point me to that file please?
![Screenshot from 2023-04-02 05-22-38](https://user-images.githubusercontent.com/74005072/229364994-b02c8f17-3b3d-44c6-84d5-de46cd3b6aa2.png)

**Comment by frodeheg** [comment]
Uhm.... that message doesn't make sense, does it?
Does your Yamaha receiver have a thermostat capability???
I suppose I should remove the message...
You're using a virtual switch for this device, right?

Anyway, all devices with the hammer icon are considered experimental devices. I was thinking we don't need translation strings on experimental devices... Hopefully they should make their way out of the experimental state as soon as possible and get rid of these debug messages. .... well, or at least I'm dependent on someone reporting that it is working.... which doesn't always happen.

**Comment by PeterKawa** [comment]
Err..... no the message doesn't make sense,while all listed devices have OnOff capabilities, and they all seem to have a hammer icon. Yes, it is a virtual switch. There are no devices listed with thermostat capabilities. It should find f.i. my tado thermostat ,shouldn't it?
And you're right about keeping things in English for experimental things. I have no smart electrical heating/cooling devices with thermostat capabilities.

**Comment by frodeheg** [comment]
Device of type: `com.arjankranenburg.virtual:virtual_switch` seem to expose different capabilities. It has been reported as both controlling an AC device (which had no onOff capability, only thermostat_mode that could either be "heat" or "off". In the other case you reported above I'm not sure what capabilities it exposes but I suspect it is of type onOff). I can probably add an auto-detection that distinguishes the two and only show the note for the thermostat. If you send a device report for this specific device it will probably help a little, but it's not required.

**Comment by frodeheg** [comment]
The change for ticket #286 ([githash](https://github.com/frodeheg/no.sparegris/commit/ba98212119ca6bed7422739163f187bc70f7ad63) ) also affect the virtual device... it seems like onoff and thermostat can be separately enabled, so it is suggested to auto-detect if both of these are available.

**Comment by frodeheg** [comment]
I feel the note is sufficient, as there is also a virtual mode device that does support switches, so it feels unnecessary to add special support for this use of the device when nobody have requested it.
