### ISSUE TITLE
Car charging not working like it says it works

### ISSUE THREAD

**Issue by dooniem** [frodeheg/no.sparegris#24]
We've had a small dialogue about this, I understood an issue was the best approach to resolve.
The flowcard for kWh that triggers start of car charging describes that the charging session will stop once the asked kWh has been offered:
![image](https://user-images.githubusercontent.com/9369839/196258735-5685b85a-ea66-4fa5-a431-29306d1d3900.png)
Inside the settings, the same concept is explained:
![image](https://user-images.githubusercontent.com/9369839/196259012-ac65007b-8a7d-4aee-917f-7be33af86f2f.png)

Yet, you **don't stop** the charging when what's asked is delivered. Only time is relevant for stopping.

My suggsestions:

- New flow card (change existing) "MINIMUM offered kWh until end time" and "MAXIMUM offered kWh until end time"
- Since I have sensed you want as few flowcards as possible, checkbox inside the settings to decide whether to stop or not

**Comment by frodeheg** [comment]
This has now been implemented for
* The new charging algorithm in #59
* Charging with flow cards

I did NOT implement it for the old charging algorithm for Easee as this will be deprecated when the new charging algorithm has been deemed stable, please be aware before reopening this again...
