### ISSUE TITLE
Possible bug after restart

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#25]
The following bug report made me wonder about two things:
* The frequency the device "Stue" turns on is way too often considering that there has been a recent poweroff
* The Homey reboot  was detected so close to the new hour that the time where device control was prevented went over into the new hour. Could this have affected the resetting of the hourly counter somehow?

(note that **always on** may also turn off in case of emergencies, although it may be that this should not have been an emergency.)

Log ID: 2022-10-18T17:53:28.462Z
App version 0.18.6

+17:53:28.462: No state from previous shutdown? Powerloss, deactivated or forced restart.
+17:53:28.622: Homey reboot detected. Delaying device control by 578 seconds to improve Zigbee recovery.
+18:5:19.612: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:5:19.810: Failed to reduce power usage by 319W (number of forced on devices: 2)
+18:8:35.977: Failed to turn on device Stue, will retry later
+18:10:34.511: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:10:34.513: Failed to reduce power usage by 614W (number of forced on devices: 2)
+18:10:49.694: Failed to turn on device Stue, will retry later
+18:10:50.403: Failed to reduce power usage by 621W (number of forced on devices: 2)
+18:11:8.062: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:11:8.065: Failed to reduce power usage by 49W (number of forced on devices: 2)
+18:11:23.800: Failed to turn on device Stue, will retry later
+18:11:24.331: Failed to reduce power usage by 33W (number of forced on devices: 1)
+18:11:42.162: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:11:42.165: Failed to reduce power usage by 41W (number of forced on devices: 2)
+18:13:36.161: Failed to turn on device Stue, will retry later
+18:15:44.126: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:15:44.128: Failed to reduce power usage by 543W (number of forced on devices: 2)
+18:15:58.899: Failed to turn on device Stue, will retry later
+18:15:59.410: Failed to reduce power usage by 42W (number of forced on devices: 1)
+18:16:15.061: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:16:15.063: Failed to reduce power usage by 14W (number of forced on devices: 2)
+18:16:31.312: Failed to turn on device Stue, will retry later
+18:16:31.956: Failed to reduce power usage by 6W (number of forced on devices: 1)
+18:16:48.600: Failed to turn off device Stue, will try to turn off other devices instead. (Error: Timeout after 5000ms)
+18:16:48.602: Failed to reduce power usage by 12W (number of forced on devices: 2)
+18:17:4.413: Failed to turn on device Stue, will retry later
+18:17:7.087: Failed to reduce power usage by 11W (number of forced on devices: 8)
+18:17:9.225: Failed to turn on device Stue, will retry later
Comment:After reboot, PB kept turning on and off my heat pump "Stue". I'm nowhere near the target (5kWh) for the hour. Pump was configured as always on. The toggling stopped after raising the ceiling to 10kWh.
+18:23:8.262: Sending log

**Comment by frodeheg** [comment]
For reference, did you by any means do this in the given interval:
* Save the settings
* Change the mode
* Change the price point
* Change the zone settings

?

**Comment by frodeheg** [comment]
Assuming you did not... I have a hunch about what could have happened

If a device is marked as unreliable during EMERGENCY_OFF operation then when retrying the operation later it is retried as TURN_OFF. TURN_OFF on the other hand unlike EMERGENCY_OFF is converted to TURN_ON if the mode state is ALWAYS_ON

**SOLUTION**: I will attempt to make sure the retried operation is exactly the same as the original operation, this will make sure such problems will not occur.

I could possibly also make sure the on-guard that prevents turning on again devices also affects the monitor that retries failed turn-on/off attempts but I am not sure this will have much effect as it does not address the problem at its root (which the above suggestion does) because if the turn-on/off guard was active the turn TURN_ON command would never have found its way into the monitor in the first place. Thus I will not attempt to change this functionality.

**Comment by ugumba** [comment]
> For reference, did you by any means do this in the given interval:
> 
> * Save the settings
> * Change the mode
> * Change the price point
> * Change the zone settings
> 
> ?

I probably saved settings, can't remember what.
I doubt the mode changed - PB was in Day mode.
The price level might have changed at the turn of the hour, but I didn't set it manually.

Come to think of it, when saving changed settings, does PB detect if mode or price level have actually been edited, or do you save all settings if one has been edited?  If the latter, i might have inadvertently changed price level manually.
