### ISSUE TITLE
Investigate why the mode is displayed incorrectly in the settings for some users

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#278]
**Origin of ticket:**
https://community.homey.app/t/app-pro-piggy-bank/66677/788?u=frodeheg

**Current status:** Awaiting user info on the following questions:
* Need a new screenshot of the browser log whenever this situation occur again.

**Affected Homeys:**
* Homey Pro 2023, v.10.1.4
* Homey Pro 2023, v.10.0.4

**Affected Devices:**
* Google Chrome
* Microsoft Edge
* Homey app on Android

**Affected versions:**
* Piggybank verion 0.21.7

**What is known so far:**
* The state itself is not affected, only the display of it in the settings window. (and as such also the state if saving again)
* Piggy-bank insights is not affected, it shows the right value.
* It (only?) affects the settings window if it has to be reloaded / if it fails the first time.

**Current theory is:**
* Alt 1: HP2023 seem to have some issues with the signalling between the HP and the interface, this reports as a success, but the data seem to be lost. I wonder if this loss of signal makes the interface proceed but without data, then possibly the data is re-requested and arrives after the interface has been updated. The log in v. 0.21.8 should be able to detect this.
* Alt 2: That some state is not reset when reloading the browser window so the browser continue to the finished loading state before everything is actually loaded.

**Comment by xExodus84x** [comment]
Dont see anything that points to my problem in the log, here's a picture

![image](https://github.com/frodeheg/no.sparegris/assets/107132233/61d36492-b46e-4e8b-b358-73f9afda6f2b)

**Comment by xExodus84x** [comment]
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/486e7c60-be11-4dc0-9c9e-95202447982e)

Is this good enough? ive double checked again that the settings are correct when using the "backup" printout, but not showing correctly in gui, 
Also get this "network request failed" alot, not sure if thats homey or your app, but dont see it on other apps (as of now)

i have Homey Pro 2023, version 10.1.4
Piggybank verion 0.21.7

**Comment by frodeheg** [comment]
"Network request failed" is not from piggy, it's from "my.homey.app"
Both of the errors are also from the my.homey.app environment...
* Failed to load resource: net:: ERR_NAME_NOT_RESOLVED and
* Uncaught (In promise) error

Is the Homey connected to a wired network or is it only using wireless? I would expect the Homey errors to go away if you connect the Homey to a wired network and try again. Then, if the bug goes away from piggy as well, it could be related.

There is nothing in the remaining log that would indicate an error when setting the GUI item. I see in the GUI that it's set to "Cold", was this also the correct mode at this instance, or was it something else in the "backup" part when the screenshot was generated?

**Comment by frodeheg** [comment]
Another note.... I see in your image that you have set the "Vaskemaskin" as a controllable unit... This doesn't sound like a good thing to do, If piggy turns it off and on multiple times during the washing cycle, wouldn't this ruin the wash? I would suggest only controlling heaters, AC and to some degree non-essential lights with piggy.

**Comment by xExodus84x** [comment]
i have the washing machine set to "always on", and it have never actually turned it off (not sure if it can do it since its going through smart things), but im going to turn it off :)

My homey is already using LAN adapter, but get the same error on wifi, never get it on any other app tho

**Comment by frodeheg** [comment]
Thanks again, as you say it's showing as Day in the GUI when it's wrong, but in the screenshot you posted earlier it was correct ("Cold"), can you make a similar screenshot of the console.log when the GUI is showing the wrong value?

> My homey is already using LAN adapter, but get the same error on wifi,
> never get it on any other app tho
> Can it be firewall/nat issue? Is there anyway i can test the connection etc.?

Hmm.... since all this traffic goes through my.homey.app, may I ask what kind of internet connection you have? Is it a mobile/satellite or otherwise wireless or low bandwidth connection? What is your ping-time to my.homey.app (mine is around 10 ms)?

**Comment by xExodus84x** [comment]
The internet line itself is not the problem, its a 1gbit Altibox fiber line, and everything els across all my other machines works fine
If there is a network issue, im thinking more in the line of nat/firewall or vlan issues

5ms ping time right now atleast
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/8549abcb-96e5-42ee-bae5-48dfc6f1d678)

**Comment by xExodus84x** [comment]
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/2560060a-490d-4461-91bf-a838716b09e7)

**Comment by frodeheg** [comment]
Hmmm... that last error response was new to me, that probably have something to do with it. I have no idea how to capture it, but I'll see if I can find some clues on the internet.

Other than that, I found another suspect in this bugfix that might be related: #264

**Comment by frodeheg** [comment]
I added some console logging in order to try to resolve what happens in version 0.21.8. If you're not at the test-version, can you please install this one and make a new screenshot of the console if you see the error again?

I also added some code to set the value differently in case that helps, so if it does not appear again, then maybe that was the solution. Please let me know if there are any changes at all...

**Comment by frodeheg** [comment]
Allright, I think I may have found the issue.
This should only affect situations when there are custom modes added and the current mode is one of the custom modes.

Apparently, when the setup interface is loaded it will proceed in this order:
1) First set the value of the mode select box
2) Then it will update the items in the mode select box, adding the custom modes.

Thus, if the mode is one of the default ones, step 1 will pass, but if the current mode is one of the custom modes, then step 1 will try to set a value that doesn't exist so the step will fail and the browser defaults to the first mode.
Then, at step 2, when the custom modes are added the value is already wrong, so it will use the new value from step 1.

I will change the order of step 1 and 2 tomorrow and publish a new fix...

(meanwhile, if you want to test my theory, you can try to set to one of the default modes and see if it works with those... Similarely set to one of the custom modes and see that it never works with those)

**Comment by xExodus84x** [comment]
First a picture of the console in 0.21.8, now it doesnt display active mode at all at first load
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/5192d573-10bf-4067-8bdc-5088729ed127)

**Comment by xExodus84x** [comment]
Here i first saved it as "night", and that sticked through several open/close cycles, then did the same with "vacation", both those worked
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/8452f34e-6fc2-45ac-aec0-619bcc450215)

**Comment by xExodus84x** [comment]
changed back to one of my custom ones, and its back to showing no active mode, but correct in config, so it seems like your on to something
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/69e0546a-34d7-4451-bcb9-84a4e954ffb4)

**Comment by frodeheg** [comment]
Allright, please try version 0.21.9 and see if I have finally fixed this issue. (sorry that it took so long)

**Comment by xExodus84x** [comment]
seems to work flawlessly now, also worked changing mode with flow
![image](https://github.com/frodeheg/no.sparegris/assets/107132233/d5f9e634-90b4-4a29-b540-b3aa1a1a0331)
