### ISSUE TITLE
MaxDrain calculated wrongly for single phase main breaker

### ISSUE THREAD

**Issue by nepse1** [frodeheg/no.sparegris#282]
Awesome app!

Single phase Volt Ampere to Watt calculation does not need sqrt(3). Could you please implement a toggle switch in the UI near main breaker Ampere for single/3-phase breaker?

Example: 50A breaker @ 230V single phase yields 11500W, not 19918W. Big difference.

https://github.com/frodeheg/no.sparegris/blob/3059e6ef15458c222cc552c7f291e4e2b1d0261a/app.js#L2183

**Comment by frodeheg** [comment]
Thank you for the report.
The main problem here is that the Easee app does not expose the number of phases. Other apps don't have access to the settings of another app. Thus, this has to be manually specified by the user.

As the current charging system is being completely rewritten in the new [piggy_charger](https://github.com/frodeheg/no.sparegris/tree/piggy_charger) branch I can add this as an option to the pairing process of the new charger controller.

**Comment by nepse1** [comment]
Actually, I don't need this for car charging. I butt up against the main breaker limit of other reasons (washer, dishwasher, oven, heating ovens, etc. peaking at the same time). I would be happy with specifying this manually. I propose: 1) Rename main breaker limit to *Watt* (possibly easiest quick fix), or 2) An appended input toggle switch for single/3-phase (easier to understand).

In my actual case, i have set the main breaker setting in the app to 28A (= 11154W 3-phase) to approximate my 50A single phase main breaker. I don't think this break anything else in the app for my usage...

Hope this helps ;)

**Comment by frodeheg** [comment]
I have now added a phase and voltage selector for the main fuse. It has only been added to the piggy_charger branch, so it will not appear in any release before the charge controller device is public.
