### ISSUE TITLE
Easee charger will not go over 11A

### ISSUE THREAD

**Issue by xenier78** [frodeheg/no.sparegris#295]
I use Sparegris to control electric car chargers (Easee) (and other things) this has worked completely painlessly for several months. But then I noticed here last week that the car wasn't fully charged in the morning. I then found out that it only charges with 11A, i.e. 2.4 kw. It has suddenly started doing this. I can't get it to go higher as long as it is controlled by piggy bank. If I exclude it from the piggy bank, I can set it up to 32A. I can also override it in the piggy bank, then it also goes up to 32. But not if the piggy bank is to control the current itself.  Wondering if it's related to some update of the app, as I haven't made any changes. I think Easee app was updated last week. I have 3 Fas IT, but the charger is locked to 1 Fas 32A

**Comment by frodeheg** [comment]
There has not been any changes to Piggy lately with regards to chargers.

However, The Easee controller has previously worked like this:
If you give it a starting current of less than 11A it will be locked to 1 Fas. If you give it a starting current of 11A or above it will be locked to 3 Fas. You can change the current after this but you can not change from 1 Fas to 3 Fas once the charging has started.

Thus, please make sure that your starting current is 11A. If it is, then there might have been changes to the Easee controller. Then I would suggest that you dissconect the charger from piggy and perform the following test:
Which starting current do you need to get 3 Fas charging? If it's not 11A I can update the app to default to the new value.

**Comment by frodeheg** [comment]
My homey is currently dead and a new one is under way in the mail. Meanwhile I am unable to post screenshots so my explanations may be a little off.
Under the car charger settings, if you enable the override, you should be able to override the start current, minimum current, maximum current, pause current and stop current.

The current should fluctuate between the min and max settings under override, but it should always start on the "start" current. You can sett these individually under the override section.

If you wonder what is actually being set, then under settings go to "Help"->"Debug" and select the car charger device. Let the option "other events" stay at "Errors only". Then you can start the charging and you will see all the interactions between piggy and the charger.

**Comment by frodeheg** [comment]
I got a new homey now. Did you resolve this issue?
Have you found out more? Was this an Easee problem or a piggy problem?

**Comment by xenier78** [comment]
Hi Frode. No, the problem seams to still exist. I need to have it to override, then it works. If I try to set it back do disabled it charge only with 11A

**Comment by frodeheg** [comment]
Can you please give it a new try with the new charge controller in test version 0.22.1 that is being launched on the night to the 6th of April?

**Comment by xenier78** [comment]
Yes , offcourse. How do install the test version?

Mvh

Audun Levin
________________________________
Fra: frodeheg ***@***.***>
Sendt: Thursday, April 4, 2024 3:54:47 AM
Til: frodeheg/no.sparegris ***@***.***>
Kopi: xenier78 ***@***.***>; Author ***@***.***>
Emne: Re: [frodeheg/no.sparegris] Easee charger will not go over 11A (Issue #295)


Can you please give it a new try with the new charge controller in test version 0.22.1 that is being launched on the night to the 6th of April?

**Comment by xenier78** [comment]
Hi Frode,

I did now test the new version with the control charger device, and I did get the two first steps green, but the third won't finish. See attached screenshot.

the response test will not Finnish.

Mvh

Audun Levin
________________________________
Fra: Audun Levin ***@***.***>
Sendt: Thursday, April 4, 2024 1:59:17 PM
Til: frodeheg/no.sparegris ***@***.***>; frodeheg/no.sparegris ***@***.***>
Kopi: Author ***@***.***>
Emne: Re: [frodeheg/no.sparegris] Easee charger will not go over 11A (Issue #295)

Yes , offcourse. How do install the test version?

Mvh

Audun Levin
________________________________
Fra: frodeheg ***@***.***>
Sendt: Thursday, April 4, 2024 3:54:47 AM
Til: frodeheg/no.sparegris ***@***.***>
Kopi: xenier78 ***@***.***>; Author ***@***.***>
Emne: Re: [frodeheg/no.sparegris] Easee charger will not go over 11A (Issue #295)


Can you please give it a new try with the new charge controller in test version 0.22.1 that is being launched on the night to the 6th of April?

**Comment by dooniem** [comment]
He's fixed the validation problems now, try again this weekend 😃

**Comment by frodeheg** [comment]
Yes, sorry @xenier78 , I forgot to notify you.

**Comment by xenier78** [comment]
The new chargecontrol seams to work, I got full effect on charging now. But it seams to be something wrong with the Penger values in the charge control, I've just charged for some minutes, and I have past 1000kr 😄

Mvh

Audun Levin
________________________________
Fra: frodeheg ***@***.***>
Sendt: Friday, May 3, 2024 11:11:23 PM
Til: frodeheg/no.sparegris ***@***.***>
Kopi: xenier78 ***@***.***>; Mention ***@***.***>
Emne: Re: [frodeheg/no.sparegris] Easee charger will not go over 11A (Issue #295)


Yes, sorry @xenier78<https://github.com/xenier78> , I forgot to notify you.

**Comment by frodeheg** [comment]
Thank you, I will close this ticket then.
The 1000x price issues has been spawned to this ticket, thank you for the report: https://github.com/frodeheg/no.sparegris/issues/354

**Comment by xenier78** [comment]
Hi Frode,

The problem with maximum charge speed to 11A seams to be back. And now i don't have any options to override it either. The charger is now locked to 11 A as long as sparegris is controlling it

Mvh

Audun Levin
________________________________
Fra: frodeheg ***@***.***>
Sendt: Monday, May 13, 2024 2:49:02 AM
Til: frodeheg/no.sparegris ***@***.***>
Kopi: xenier78 ***@***.***>; Mention ***@***.***>
Emne: Re: [frodeheg/no.sparegris] Easee charger will not go over 11A (Issue #295)


Thank you, I will close this ticket then.
The 1000x price issues has been spawned to this ticket, thank you for the report: #354<https://github.com/frodeheg/no.sparegris/issues/354>
