### ISSUE TITLE
Service button for AC devices

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#30]
It is very inconvenient to change the filters of AC devices controlled by PB. This is because PB instantly tries to turn the device on again when it has been turned off.

My original proposed solution: In the help section add an AC section with a single button: "Disable all AC devices and do not resume control before they are manually turned on again".

Community proposal (@Exerqtor):
> * Making a new component for Sparegris called “Override( or something like that )”. When adding this device we get prompted the list off units controlled by Sparegris. We choice one (or maybe several, if possible)
> * Then with the component added when we access it we have a list much like how the Sensibo app is setup. In that list we choose what unit we want to override. Then get the option to “turn off” or “turn on”, this then overrides the other Sparegris settings for the selected unit and toggles the unit to “off” when turned selected to do so. And when told to go “on” again, it returns to normal operation.

Origin of request: https://community.homey.app/t/app-pro-piggy-bank/66677/188?u=frodeheg

The community proposal sounds very interesting, although maybe a bit too involved for newcomers. I suppose I need to consider adding both proposals.

**Comment by Exerqtor** [comment]
I agree it might be involved / too much with it's own app for that one feature. What about adding it as an tab in the insight app(if possible)? Like how it's done in the Sensibo app, a pulldown menu to select what AC you want to turn off, and a off / automatic function once a AC is selected.

Screenshots from the Sensibo app for referance:

Swap out "Termostat modus" with "Device" 
![Screenshot_20221021-070702](https://user-images.githubusercontent.com/41635644/197116848-e88e7648-2bf7-45d5-8902-d79f1b7fb468.png)

Swap out "Automatisk, Varme, Avkjøle, Av" with "Automatic, Off" 
![Screenshot_20221021-070710](https://user-images.githubusercontent.com/41635644/197116864-f2643d0d-6b34-4fa5-b913-bb852689e6e9.png)

**Comment by ugumba** [comment]
Another option: serve a simple "servicing/overrides" web page which can be accessed on the local wifi.
For each device, this page provides links/buttons to override automatic operation (constant on/off and cancel as a start).

For access over the internet, users would have to enable port forwarding, but then we'd need a certain level of security.  (Is it possible to piggy back on Homey authentication?)

(I use this to get Prometheus metrics into an azure VM, so it can be done.)

**Comment by frodeheg** [comment]
Are you saying that the Prometheus app is hosting a web server or are you using webhooks @ugumba ?

**Comment by frodeheg** [comment]
I think this feature is not directly AC related. Some people might want to override the temperature controls too if they cannot bare it being too cold when the price points has been extremely high for several hours in a row. Although, that defeats the purpose of controlling when to use the energy it could be very good reasons for overriding it, like visitors are coming or you are going to arrange a party.

**Comment by ugumba** [comment]
> Are you saying that the Prometheus app is hosting a web server or are you using webhooks @ugumba ?

The first!  I thought that was pretty cool. In theory, any app could serve its own admin UI outside the obvious limitations of the normal Homey UI.  Auth and internet access are probably the hard parts.

**Comment by frodeheg** [comment]
Nice idea, but I view it as a separate feature so I branched it out as a separate issue. It can be further discussed here: #36

Then we can keep this thread about AC service

I wonder, could the AC service be combined with the zone-control feature that lets you override zones. I can let AC-devices come up alongside the zones?

**Comment by Exerqtor** [comment]
> Nice idea, but I view it as a separate feature so I branched it out as a separate issue. It can be further discussed here: #36
> 

Agreed, this is more to mitigate the shortcommings of the current Homey UI than specific for a "simple" service/override function. 

> I wonder, could the AC service be combined with the zone-control feature that lets you override zones. I can let AC-devices come up alongside the zones? And even let you enable/disable the zones/AC in the zone overview page, not only through flows...
> 
> Or is it better as a capability in the insights app as was suggested above?

I think being forced to shut down whole zones to service one unit is a little extreme to be honest. Sure it could be a cool extra feature, but i think a pr. device controll inside the insights app (maybe rename the insight app to something more fitting as part of adding more functions to it even) would be a cleaner way to go. I haven't had a look at how constricted the app dev. for homey apps are so i don't know how much is possible though.

**Comment by frodeheg** [comment]
> I think being forced to shut down whole zones to service one unit 
I wasn't suggesting to shut down the entire zone, just to combine the override feature / page into one, so both for zones and devices. I find it a bit confusing if there are multiple override pages then you can easily get lost why your devices are not enabled

**Comment by dooniem** [comment]
> if you click on the cogwheel at the top there is a menu option named "Maintainance" (Vedlikehold).

Hear hear.
I have 2 ACs and always just pull the breaker when doing maintenance. But for people having the breaker board in an inconvenient place, I think accessing the insight device options is 4 times as quick as clicking:

Open Homey->Click More->Click Settings->Scroll-scroll->Click Piggy Bank-> Wait-Wait->Find correct tab for maintenance
One would think in most cases, even when the AC and the breaker board are several floors apart, it's quicker to find the breaker board.

**Comment by Exerqtor** [comment]
> > I think being forced to shut down whole zones to service one unit is a little extreme...
> 
> I wasn't suggesting to shut down the entire zone; I was suggestion to combine the override feature / page with AC service into one single feature / page, so both for zones and devices. I find it a bit confusing if there are multiple override pages then you can easily get lost why your devices are not enabled
> 
> > but i think a pr. device controll inside the insights app
> 
> I wonder if the most fitting place would be when you open the insight device, if you click on the cogwheel at the top there is a menu option named "Maintainance" (Vedlikehold). In the homey spirit I believe Athom want such maintenance actions to be listed there.

Having it within the settings on Innsikt/Insight sounds like a good thing to me, way easier than having to go the app-settings route.

Would it be possible to handle/select what components that get listed inside said maintenance section from app-settings maybe? 

Maybe an extra checkmark on the devices we select under "Kontrollerbare-enheter" called maintinance switch. If it gets enabled they will show up in the Maintinance section of the Innsikt/Insight settings? 🤔

**Comment by frodeheg** [comment]
> Would it be possible to handle/select what components that get listed inside said maintenance section from app-settings maybe?

That would not be possible. Maintenance actions are by definition capabilities and all capabilities are pre-defined. There is no such thing as a run-time defined capability. (although, not sure if a maintenance action can take parameters, if they can then that would be another option)

My thinking goes like this: If you have time to do AC maintenance then you probably want to do it for all at the same time to save time and cut down on the number of maintenance events. The maintenance action turns off **all** ACs and then will not be controlled again before they are turned on again. Control is resumed *individually* for each AC.

So that's for the maintenance action... as for the overriding of any device, I'll add this later, but you can consider the AC maintenance action as some pre-work for the overriding feature as the same functionality will be used for that.

**Comment by frodeheg** [comment]
A service action has been made in the above check-in. It does work, however it probably need the following updates before it can be considered complete:
* Must be made persistent across app restarts (in case I send out an app update during AC maintenance)
* Must list the affected devices on the override page (former Zone page)
* The former Zone Page should be renamed to Override Page

**Comment by Exerqtor** [comment]
Awesome! Looking forrward to trying it out, will it be any sort of warning prompt on the device logo (like the one when needing a manual shutdown) when servicemode is active? Could be nice with an indicator on the mainscreen of Innsikt too, "Service: Ja/Nei". 

I only have three AC's so i don't need it, but i'm sure some deployments have way more, and it could be an nice reminder if it's on or not.

**Comment by Exerqtor** [comment]
Also, should these changes be live now? I just installed the test/experimental version and the maintenance tab still ain't nowhere to be seen 😥

**Comment by frodeheg** [comment]
No, it's not live yet (not even in the debug version)
