### ISSUE TITLE
2 decimals option for prices. 

### ISSUE THREAD

**Issue by Exerqtor** [frodeheg/no.sparegris#39]
Pretty sure the title is quite self descriptive, but an option to select 2 decimals OR 5 decimals for Insight?

I feel like having 5 decimals clutter up the screen a little bit to much, and tbh anything lower than "1øre" ain't thst big of a deal 😅

**Comment by frodeheg** [comment]
But what about when the prices get really cheap... about 0.0001 per kWh?

(ok, point taken) ;-)

**Comment by Exerqtor** [comment]
🤣

**Comment by frodeheg** [comment]
Actually, I thought I already did this, as you can see in the definition of the capabilities showing currencies: https://github.com/frodeheg/no.sparegris/blob/main/.homeycompose/capabilities/piggy_money.json
I already stated that `"decimals": 2,`

Wonder if it's a bug with the homey SDK

**Comment by Exerqtor** [comment]
> Actually, I thought I already did this, as you can see in the definition of the capabilities showing currencies: https://github.com/frodeheg/no.sparegris/blob/main/.homeycompose/capabilities/piggy_money.json I already stated that `"decimals": 2,`
> 
> Wonder if it's a bug with the homey SDK

I'm pretty sure you have to change it here Frode 😅:

https://github.com/frodeheg/no.sparegris/blob/main/drivers/piggy-bank-insights/driver.compose.json

`"decimals": 5,`

**Comment by Exerqtor** [comment]
Made a pull request with 2 decimals ✌️
https://github.com/frodeheg/no.sparegris/pull/40

**Comment by frodeheg** [comment]
Thanks :-)

**Comment by Exerqtor** [comment]
See that the version is live now, but somehow "high price limit" still have 5 decimals 🤔 i've had a quick look at the code, but it looks like you've moved stuff around so i can't find it 😅

![Screenshot_20221024-074626](https://user-images.githubusercontent.com/41635644/197456231-4b11290b-3ac5-439f-9bac-73857cbd8d79.png)
