### ISSUE TITLE
"Disable override" flow card does not reset temperature

### ISSUE THREAD

**Issue by ugumba** [frodeheg/no.sparegris#47]
Thanks for the new override flow cards!
I use it to start/stop heating for drying clothes in a room which is normally cold.
The "override with manual temperature" card is a perfect fit.

However, the "disable override" card does not reset the temperature - I haven't waited more than about 10 minutes, but I assume it will be reset at the next price point or mode change (I've verified that the override is no longer active).

**Comment by frodeheg** [comment]
Thanks, for spotting, will fix it right away.
