### ISSUE TITLE
Inconsistent price point title for low/cheap

### ISSUE THREAD

**Issue by Gakk** [frodeheg/no.sparegris#60]
ℹ️ _**Note:** I have encountered this issue using Norwegian language, but after inspecting the code I believe this also can be the issue for English language. Since this issue definitely affects Norwegian language, the Norwegian words directly related to the issue are not translated._

The flow trigger card for change in price point has a tool tip showing that the tag can have the values '_Dirt cheap_', '_Low_', '_Normal_', '_High_' or '_Extremely high_' ([source code](https://github.com/frodeheg/no.sparegris/blob/main/app.json#L240-L242)):

![image](https://user-images.githubusercontent.com/5013909/200194048-32ae3233-beff-472f-a698-71cedc6bbfdb.png)

But the second value actually seems to be '_Cheap' ('Billig_') instead of _'Low' ('Lav')_:

![image](https://user-images.githubusercontent.com/5013909/200194708-e8a9210b-08f9-47c2-a402-379f81621b3f.png)

This was also confirmed using flow cards (where I discovered this issue, as my water never heated on low price 😟):

![image](https://user-images.githubusercontent.com/5013909/200194834-d97ff926-818e-4b79-9477-f0c04511dd0a.png)

Since there is an inconsistency, the easiest thing would be to change the tool top tekst from 'Low' to 'Cheap', as is the actual value the field contains. This would also not break anybody's flows 😇 ... but it seems that in other places the word 'Low' is also used.

Checking for the price point using string comparing is not the best, and in fact you do supply a condition card for this. But this also has the choice for '_Low_' ('_Lav_') ([source code](https://github.com/frodeheg/no.sparegris/blob/main/.homeycompose/flow/conditions/the_price_point_is.json#L28-L30)):

![image](https://user-images.githubusercontent.com/5013909/200195041-3e4056d2-b302-40e2-8f21-bda3cb115650.png)

**I believe the app should have a cleanup of 'Low' vs. 'Cheap', and then probably use 'Cheap' all the way?**

Please let me know if you would like me to contribute with a pull request 😇

**Comment by frodeheg** [comment]
A pull request would be nice, thanks for the offer.

As long as noone gets their flows broken I am happy. E.g. if a flow card will need incompatible changes then please just mark it as deprecated and create a duplicate flow card with the actual changes.

Please remember to add yourself to the "developers" section in the app manifest if you want the glory ;-)

**Comment by frodeheg** [comment]
As this is the only remaining known bug I will attempt to fix this today.

**Comment by frodeheg** [comment]
It seems like you have done something wrong, because the tag from the "when" card for "Prispunkt endret seg" is never return "Billig" as you claim above, it is always as it says "Low". It is likely that you might have selected the tag from the device and not the flow card, which will return a number and as such won't be usable. However this does not return "Billig" either, so I can't see how you would have experienced this...

Nevertheless it's good to clean things up for consistancy.

**Comment by frodeheg** [comment]
All changes has been included in version 0.19.5 which is out for testing here: https://homey.app/a/no.sparegris/test

**Comment by Gakk** [comment]
I am really sorry I could did not have time to look at a pull request, as the last two weeks have been crazy with other work 😟

I recreated some quick flows for the screenshots in this issue, and looks like made an error there. I never tested the flows created just for screenshots 😇 But a cleanup for consistency was good nevertheless.

Thanks for fiksing this 🙂🚀

**Comment by frodeheg** [comment]
Thanks for reporting, hope I didn't break anything ;-)
