### ISSUE TITLE
Mill ovens accept temp floats of 0.5, Piggy seems to read set temp as Integer

### ISSUE THREAD

**Issue by dooniem** [frodeheg/no.sparegris#83]
Since the Mill app is more or less dead, I updated the app to show correct reading of temperature (it was multiplied with 100)
and changed this code:
```
onCapabilityTargetTemperature(value, opts, callback) {
    debug(`onCapabilityTargetTemperature(${value})`);
    const temp = Math.ceil(value);
    if (temp !== value && this.room.modeName !== 'Off') { // half degrees isn't supported by Mill, need to round it up

```
to:
```
onCapabilityTargetTemperature(value, opts, callback) {
    debug(`onCapabilityTargetTemperature(${value})`);
    const temp = Math.round(value / 0.5) * 0.5; //Math.ceil(value);
    if (temp !== value && this.room.modeName !== 'Off') { // I believe half degrees now are supported
```
Then I installed the app through CLI as experimental.

**Now** at least when I go through flow cards, setting 18.5 will result in 18.5°C.
But Piggy Bank is not able to follow suit.
Setting 18.9 results in 18°C.

I know you have made edits to support especially Mill ovens, I don't know what you did, but it seems you did something to the target_temperature?

I don't know if only me having this edit, and changing this in Piggy, will result in trouble for those who don't have this edit?
What comes to mind after reading this? (except for me being picky about decimals..)

**Comment by frodeheg** [comment]
The definition on how to treat devices are in 'common/devices.js'

there you can see under 'com.mill:mill'
It's defined with
`    tempStep: 0.5`

Thus, how you managed to tell Piggy to set til to 18.9 sounds a bit odd... You should be able to set 18.5 in piggy though... Setting half degrees works on my Heatit ztrm3 and it's the exact same logic. They are both defined with tempStep: 0.5 in the devices.js

**Comment by dooniem** [comment]
Heh, I should have searched for "Mill" inside the repository first. But OK. 

> Thus, how you managed to tell Piggy to set til to 18.9 sounds a bit odd... 

Not sure if I follow. But if this should not be possible, it is:
![Animation](https://user-images.githubusercontent.com/9369839/202420968-4cbbbbbf-e387-4bf4-8ae5-68d764f69884.gif)

If I disable Piggy and use flowcards, set 21.5, the Mill app says 21.5 for target temperature.
If I set 21.5 where I put 21.9 in the GIF above, the target temperature reported by oven/Mill app is 21. It's somehow truncated/read as int...?

**Comment by frodeheg** [comment]
Ah, ok, yes, those html input type number boxes doesn't behave the same in all browsers.
Anyways, are you sure you used the right punctuation? It may be that it should have been ",". I think it depends on your locale setting.
Also, I am a bit puzzled about your video, seems like the onExit from the input element happens after you click on the save button (because the reminder at the top get shown after the click), which is a bit odd, but could mean that the setting wasn't actually saved.

**Comment by dooniem** [comment]
If I use “.” in browser, app on iOS shows “,”. So I guess it’s more or less handled correctly locale wise. But the ovens still don’t adjust their target temperature to reach ie 21,5° as far as my testing goes. 

What complicate things is that the Homey integration is written before Mill released their Gen3 ovens. If I understand their “OpenAPI” correctly, they have at least added functionality, not sure if different basics… When Tibber controls Mill they activate what Mill call “control unit individually”. If I manually activate that, Piggy isn’t able to control the oven. What is also weird is that Piggy seem to control “the room” (zone) not the actual oven. While using flow cards it seems I control the oven and not the zone…Then add to the facts I have edited the Homey integration to support decimals, while the code has a comment that it’s not supported. Making me unsure whether or not it’s actually fully supported in the Gen1 (or Gen2?) API used in the integration…But as I mentioned, seems to work in flows 😅 A bit of a ramble there. Not sure it provides you with any input on how to potentially solve this?

**Comment by frodeheg** [comment]
You know.... it seems like I lied... I can't get mine to be at .5 either.... It was working at some point but it does not now...
So.... I will fix this in the evening as I have reproduced the issue.
