### ISSUE TITLE
Add “controlled” to the list of override options

### ISSUE THREAD

**Issue by dooniem** [frodeheg/no.sparegris#88]
In the flowcard “override unit” add the option “controlled”, as my unit defaults to always off.

Oil heater on smart plug, lots of watts, it would be perfect if Piggy onoffed/controlled it since it’s turned on and off by flows already

**Comment by frodeheg** [comment]
I had a hard time understanding why this would be useful at first, but I think I get it now.

So you have one mode where it is "Controlled", then another mode where it is "always off".... then some external event wants to make it controlled again in this circumstance only.

Ok, I'll add it.

**Comment by dooniem** [comment]
Phew. Thanks. I set "always off" inside the settings. When flow turns on oven, set to controlled. When flow turns oven off, disable override was my thought. Then it would revert back to always off as the original setting?

**Comment by frodeheg** [comment]
Looking at the code... did override option "on" and "off" actually work before ???

**Comment by frodeheg** [comment]
I'll leave the testing to you...

**Comment by dooniem** [comment]
It does not show up in the menu listing active overrides. And it does not change the icon in modes to controlled. So I have no visual clue that it’s working. 
But I can put it to low priority and boost power consumption to see if it off’s?

**Comment by dooniem** [comment]
My test indicates it doesn't turn off. 
Had set the plug to lowest priority. Sent a flow to override: set plug to "controlled", Icon still said "always off".
When consumption went up, the higher prioritized devices started turning off. Plug stayed on.

**Comment by frodeheg** [comment]
Not in the override list... that must be a bug... I'll reopen

**Comment by frodeheg** [comment]
I added testing code for the second issue, but I cannot reproduce that the device does not turn off.

You should note though that if there has been registered a single signal failure on a device it will be tried last (until it does not have signal failures). Thus it could have been a random instance of that...

**Comment by dooniem** [comment]
`Thus it could have been a random instance of that...`
Can I test for this?

Now it shows up in the list of overrides. But it still doesn't turn off as expected.
I sent a log with the details for my plug through your app.
Just so we're clear, this is my setup before sending "override controlled".
![image](https://user-images.githubusercontent.com/9369839/203306718-8811b49b-e0a7-41bf-afb2-f69338a77167.png)
