### ISSUE TITLE
Charging with 3 phases must be carefully controlled

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#94]
Some experimentation has shown that:
* If charging with 1-phase at <11A and goes above 11A then charging will still stay at 1 phase.
* If charging is disabled = 0A and then goes above 11A then charging will go to 3 phases.

Thus, the current solution going up and down dynamically (and always starting at the lowest current) will lose the ability to charge at 3 phases.

Whether this is intended behavior from Easee or not needs to be sorted out before any actions to proceed will have to be taken.

**Comment by ThomasEdvardsen** [comment]
To give some context:
The problem occurs when you charge with 3-phase of more than 11A, and limit the charging current to below 11A. The Easee charger then switches to using 1-phase, but does not switch back to 3-phase if you increase the charging current to over 11A again.

https://support.easee.com/hc/no/articles/4413169971345-Kan-bilen-min-lade-p%C3%A5-3-fase-

**Comment by frodeheg** [comment]
The override feature I just completed should allow us to circumvent this while we evaluate how to address this going forward.
Further changes should be discussed here: https://github.com/frodeheg/no.sparegris/discussions/97
