### ISSUE TITLE
Enhancement: Make a "charge Session" tag, JSONstring?

### ISSUE THREAD

**Issue by dooniem** [frodeheg/no.sparegris#95]
Is it tedious to implement a tag, I’m thinking JSON.stringify(), that’s updated after a charge is ordered, and after a schedule recalc, that let us access planned hours for charging inside flows?

I don’t know the char limit for a variable. But if it’s high you could add more info. Then us users can build our own device cap unit or access data that’s only visible to us through a lot of clicks and loading inside the settings?

Unless you are building a “Piggy car charge insight”-device anytime soon?

**Comment by frodeheg** [comment]
What would you prefer?
* A JSON-string
* or a condition card similar to the one I did for future-prices-unavailable condition card... with the hours into the future parameter - which return true/false if charging is enabled for that hour.

I feel option 2 is more consistent with the other condition, but I'm not sure if it will suit your needs.

How will this help you actually? Is it about timing washing-machines etc. so they don't collide with the interval? If you're charging with the kWh flow it will just add new hours on the fly if it didn't get enough Power.

**Comment by dooniem** [comment]
It’s definitely a “nice to have” rather than a need to have. Easy access to data. I know it’s available inside the settings. But as I said, lots of clicks and waiting. 
My first use would be to add the starting hour to the push notification I receive when plugging in and auto order a charge. Just for the hell of it I’d put the number of hours planned charging as well. For what? For the pleasure of knowing and for bragging rights when possible 😇 I think you don’t need that many tags if you JSON.stringify some data and let us tweak and experiment ourselves.

`I have this one pretty high up on the priority list:
https://github.com/frodeheg/no.sparegris/issues/20` 
You haven’t replied to my comment about making a new device. With such a tag as asked for, people looking to learn and experiment inside their Homey could make stuff like this on their own through the app Device capabilities. But we would need tags to access data
![B851F6C5-7E3B-4C55-AE46-872558FB73DC](https://user-images.githubusercontent.com/9369839/204078272-b467a32b-831a-4994-b23c-e65f7e98610e.jpeg)

**Comment by dooniem** [comment]
I see I didn’t answer your actual question. I’d prefer a JSON. But if you go for a card, I could write a HS that iterated hours and handle each true and store them in a JSON myself. Harder, but serves the purpose of accessing charge data through flows

**Comment by frodeheg** [comment]
Hmm.... You're not actually looking for a flow card, you're looking for a "[Global Token](https://apps.developer.homey.app/the-basics/flow/tokens#global-tokens)"
That will not disturb the less experienced Homey users, so I guess that can be done.

**Comment by dooniem** [comment]
Ah, yes. I thought they were just named tag’s 😅 Come to think of it, remaining current as a global token would be nice too. Mainly for an end report-push notification or timeline, but it also make it possible to create stats pr. hour for those who like such stats 😍

**Comment by frodeheg** [comment]
Here is an example json-string, does it look ok?
`{"cycleStart":"2023-07-02T01:00:00.000Z","cycleEnd":"2023-07-02T08:00:00.000Z","cycleType":2,"cycleRemaining":3,"cycleTotal":3,"currentPlan":[null,3750,null,null,null,3750,3750],"originalPlan":[null,3750,null,null,null,3750,3750],"actualCharge":[null,null,null,null,null,null,null],"actualPrices":[0.3,0.2,0.5,0.9,0.8,0.1,0.2],"currentIndex":0}`

**Comment by dooniem** [comment]
I guess this is a smart way, enable lots of information to be had with some side scripts. Will this global token come with the charger unit, or are they separate?

**Comment by frodeheg** [comment]
It comes with the new charger controller device. It will be a global token, one for each controller device.

**Comment by frodeheg** [comment]
Confirmed working json-string with latest update, closing ticket.
